/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.displayedE10SPrompt.1", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.updateIntroShown", true);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "ZA");
user_pref("browser.search.region", "ZA");
user_pref("browser.slowStartup.averageTime", 7827);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20150609081918");
user_pref("browser.startup.homepage_override.mstone", "40.0a2");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("browser.taskbar.lastgroupid", "FFD4EDB6BAA7D4C3");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"developer-button\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"webide-button\",\"firebug-badged-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("browser.uitour.seenPageIDs", "[[\"dev-firstrun-35.0a2\",{\"lastSeen\":1433921187619}]]");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1434007573603");
user_pref("datareporting.policy.firstRunTime", "1433921173602");
user_pref("datareporting.sessions.current.activeTicks", 9);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 7121);
user_pref("datareporting.sessions.current.main", 41);
user_pref("datareporting.sessions.current.sessionRestored", 7853);
user_pref("datareporting.sessions.current.startTime", "1433921173088");
user_pref("datareporting.sessions.current.totalTime", 64);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"2.0.10\",\"type\":\"extension\",\"descriptor\":\"C:\\\\Users\\\\Raymond\\\\Documents\\\\NetBeansProjects\\\\Emor\\\\web_root\\\\assets\\\\firefox-profile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:40.0a2");
user_pref("extensions.firebug.currentVersion", "2.0.10");
user_pref("extensions.firebug.toolbarCustomizationDone2", true);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "40.0a2");
user_pref("extensions.lastPlatformVersion", "40.0a2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Firefox Developer Edition\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"40.0a2\",\"st\":1433918166144,\"mt\":1433746061205}},\"winreg-app-global\":{\"fiddlerhook@fiddler2.com\":{\"d\":\"C:\\\\Program Files (x86)\\\\Fiddler2\\\\FiddlerHook\",\"e\":false,\"v\":\"2.4.9.7\",\"st\":1417099294007,\"mt\":1416625068000},\"FFPDFArchitectConverter@pdfarchitect.com\":{\"d\":\"C:\\\\Program Files (x86)\\\\PDF Architect\\\\FFPDFArchitectExt\",\"e\":false,\"v\":\"1.0\",\"st\":1384240916758,\"mt\":1365437022000}},\"app-profile\":{\"firebug@software.joehewitt.com\":{\"d\":\"C:\\\\Users\\\\Raymond\\\\Documents\\\\NetBeansProjects\\\\Emor\\\\web_root\\\\assets\\\\firefox-profile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"e\":true,\"v\":\"2.0.10\",\"st\":1433921210485}}}");
user_pref("gecko.buildID", "20150609081918");
user_pref("gecko.mstone", "40.0a2");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1433921173);
user_pref("toolkit.telemetry.cachedClientID", "092ef076-ddda-4e63-a6dc-fe586d8fe1ed");
user_pref("toolkit.telemetry.previousBuildID", "20150609081918");
