---
- name: Set up the MOTD
  template: dest=/etc/motd src=motd.j2 owner=root group=root mode=0644
  sudo: True

- name: Update our apt cache
  apt: update_cache=yes
  sudo: True

- name: Install Vim
  apt: name={{item}} state=latest
  with_items:
    - vim
  sudo: True

- name: Have SSH user go to /vagrant by default
  lineinfile: dest=/home/vagrant/.profile insertafter=EOF line="cd /vagrant"
