---
- name:  Clone clean repository into 'release' folder
  shell: git clone git@github.com:phpDocumentor/phpDocumentor2.git release

- name:  Set commit author name and mail address
  shell: "{{ item }}"
  with_items:
      - git config user.name phpDocumentor
      - git config user.email info@phpdoc.org
  args: { chdir: release }

- name: Install all dependencies using Composer
  shell: composer install -o --no-dev --prefer-dist -n
  args: { chdir: release }

- name: Increment version number and register number
  shell: "{{ item }}"
  with_items:
      - wget -nc https://github.com/mvriel/Versioner/releases/download/1.0.0/versioner.phar
      - php versioner.phar increment -p {{ release_type }} VERSION
      - rm versioner.phar
  args: { chdir: release }

- name: Retrieve new version number
  shell: cat VERSION
  register: VERSION
  args: { chdir: release }

- name: Store new version number
  shell: git commit VERSION -m "Upped version number to {{VERSION.stdout}}"
  args: { chdir: release }

- name: Update master with develop branch
  shell: "{{ item }}"
  with_items:
      - git push origin develop
      - git checkout master
      - git merge develop
      - git push origin master
  args: { chdir: release }

- name: Tag new version
  shell: git tag v{{ VERSION.stdout }}
  args: { chdir: release }

- name: Tag new version
  shell: git push origin --tags
  args: { chdir: release }

- name: Create PEAR package
  shell: phing deploy:package -Dversion.stability=stable
  args: { chdir: release }

- name: Move PEAR package to channel folder
  shell: mv phpDocumentor-{{ VERSION.stdout }}.tgz /var/www/pear.phpdoc.org/web/
  args: { chdir: release }

- name: Register new PEAR package with channel
  shell: ./pirum add web web/phpDocumentor-{{ VERSION.stdout }}.tgz
  args: { chdir: /var/www/pear.phpdoc.org }

- name: Create PHAR file
  shell: "{{ item }}"
  with_items:
      - wget -nc https://github.com/box-project/box2/releases/download/2.4.4/box-2.4.4.phar
      - php box-2.4.4.phar build
      - rm box-2.4.4.phar
  args: { chdir: release }

- name: Deploy phar to website
  shell: mv phpDocumentor.phar /var/www/phpdoc.org/web/phpDocumentor.phar
  args: { chdir: release }

- name: Archive new phar to archive folder
  shell: cp /var/www/phpdoc.org/web/phpDocumentor.phar /opt/artifacts/phpdoc.org/phar/phpDocumentor-{{ VERSION.stdout }}.phar
  args: { chdir: release }

- name: Update symlink to latest phar file
  shell: ln -fs /opt/artifacts/phpdoc.org/phar/phpDocumentor-{{ VERSION.stdout }}.phar /opt/artifacts/phpdoc.org/phar/phpDocumentor-latest.phar

- name:  Remove 'release' folder
  shell: rm -rf release
